
general.import = [
  "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
general.live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "Cascadia Code NF"

[window]
opacity = 0.8
